; Listing generated by Microsoft (R) Optimizing Compiler Version 19.29.30148.0 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

msvcjmc	SEGMENT
__34882F14_Math@cpp DB 01H
msvcjmc	ENDS
PUBLIC	?Multiplay@@YAHHH@Z				; Multiplay
PUBLIC	__JustMyCode_Default
EXTRN	__CheckForDebuggerJustMyCode:PROC
;	COMDAT pdata
pdata	SEGMENT
$pdata$?Multiplay@@YAHHH@Z DD imagerel $LN4
	DD	imagerel $LN4+42
	DD	imagerel $unwind$?Multiplay@@YAHHH@Z
pdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?Multiplay@@YAHHH@Z DD 040a01H
	DD	06340aH
	DD	07006320aH
xdata	ENDS
; Function compile flags: /Odt
;	COMDAT __JustMyCode_Default
_TEXT	SEGMENT
__JustMyCode_Default PROC				; COMDAT
	ret	0
__JustMyCode_Default ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?Multiplay@@YAHHH@Z
_TEXT	SEGMENT
a$ = 48
b$ = 56
?Multiplay@@YAHHH@Z PROC				; Multiplay, COMDAT
; File C:\Users\Laniakea\Documents\cppcode\VS\HelloWorld\HelloWorld\Math.cpp
; Line 2
$LN4:
	mov	QWORD PTR [rsp+8], rbx
	push	rdi
	sub	rsp, 32					; 00000020H
	mov	edi, ecx
	mov	ebx, edx
	lea	rcx, OFFSET FLAT:__34882F14_Math@cpp
	call	__CheckForDebuggerJustMyCode
	imul	edi, ebx
	mov	rbx, QWORD PTR [rsp+48]
	mov	eax, edi
; Line 6
	add	rsp, 32					; 00000020H
	pop	rdi
	ret	0
?Multiplay@@YAHHH@Z ENDP				; Multiplay
_TEXT	ENDS
END
